Feat: Add finer control over headline depth.
turulix/obsidian-folder-index pull request #66
Opened 2023-10-17 06:19 UTC by MediosZ

This PR allows users to set the depth of headlines displayed,  so that the users don't have to choose between zero and infinity.

By default, all headlines are displayed, keeping the behavior consistent.

2023-10-17 11:48 UTC, turulix commented
The indent level here, means how far each line is indented and does not "filter out" something like h6 or h5, if this was the intention. As seen in this Screenshot, where Test1 should still be shown.
![image](https://github.com/turulix/obsidian-folder-index/assets/28957605/1e175de3-baf1-4a55-8b57-950df488bb93)

 Maybe we could rename this to "Recursion Limit", with it being unlimited by default.
 
 If you want to filter out h6 / h5 and so on, you would need to check
https://github.com/turulix/obsidian-folder-index/blob/cedc1b400ff25d046671491b102c7df4fb4b9dee/src/types/MarkdownTextRenderer.ts#L74C1-L81

if the `headerWrapper.header.level` is <= The requested header depth

2023-10-17 11:51 UTC, turulix requested changes

2023-10-17 11:51 UTC, turulix commented on src/models/PluginSettingsTab.ts
> +			.setName("Headline Depth")
Rename to Recursion Depth, maybe?

2023-10-17 11:51 UTC, turulix commented on src/types/MarkdownTextRenderer.ts
> +				if (indentLevel < this.plugin.settings.headlineDepth) {
Filters out any things indented more than `headerlineDepth` which does not nessesarily equal the header level

2023-10-17 13:49 UTC, turulix commented
You need to enable 
![image](https://github.com/turulix/obsidian-folder-index/assets/28957605/5fb1da46-0ba9-4eba-b293-64047aee8b4e)

2023-10-17 13:49 UTC, MediosZ commented
Yeah, I didn't consider the recursive sub folders...
I will try to solve this!

2023-10-18 10:12 UTC, MediosZ commented
Since we are showing folders and headlines at the same time, maybe it's good to have two limits for folders and headlines.
Then the users will be able to control the depth of the folders and the depth of the headlines separately.

2023-10-18 13:09 UTC, turulix commented
Sounds like a good idea to me :)

2023-10-22 01:50 UTC, MediosZ commented
I think it works now 😄

2023-10-27 02:20 UTC, turulix commented
Currently sick, will deal with this once im healthy again

2023-10-27 02:22 UTC, MediosZ commented
Sorry to hear that, hope you get well soon!

2023-11-03 15:11 UTC, turulix approved these changes

2023-11-03 15:12 UTC, merged